[package]
name = "vpn_config_parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "vpn_config_parser"
crate-type = ["cdylib"]

[dependencies]
nom = "7.1.3"
pyo3 = "0.22.0"
