[package]
edition = "2021"
name = "vpn_config_parser"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib"]
name = "vpn_config_parser"

[dependencies]
nom = "7.1.3"
pyo3 = "0.22.0"
